### ISSUE TITLE
Can it work with --experimental-specifier-resolution=node  ?

### ISSUE THREAD

**Issue by thelinuxlich** [antfu/esbuild-node-loader#1]
Without this flag we need to import typescript files explicitly and VSCode shows errors on it:

![image](https://user-images.githubusercontent.com/5043/121049755-5fb65380-c78e-11eb-865c-0b96edbd7b83.png)

**Comment by antfu** [comment]
Now in 0.1.0, it should just work (no need for `--experimental-specifier-resolution=node`)
