### ISSUE TITLE
Support for `.js` extension

### ISSUE THREAD

**Issue by thetutlage** [antfu/esbuild-node-loader#20]
Not sure if it is the job of this package to handle `.js` files. However, I am using this package to run my tests and using `tsc` to create the distribution build.

TypeScript forces the import file extension to be `.js` and not `.ts`, which does not work with this package. For example:

Following works with `esbuild-node-loader`, but `tsc` does not compile it

```ts
import Foo from './foo.ts'
```

Following works with `tsc`, but not with `esbuild-node-loader`.

```ts
import Foo from './foo.js'
```

**Comment by hanayashiki** [comment]
it should work now.

**Comment by thetutlage** [comment]
Thanks :)
