### ISSUE TITLE
A mode that disallows .ts and no extension files

### ISSUE THREAD

**Issue by thetutlage** [antfu/esbuild-node-loader#27]
Hello Again 👋

I use `esbuild-node-loader` mainly for running tests and development and still rely on TypeScript `tsc` for creating the final distribution build. 

Quite often I run into this problem where I forget to add extension `.js` to an imported file, run my tests using `esbuild-node-loader` and everything works fine. Then I create the distribution build, publish the package on npm and boom everything breaks because the `tsc` does not rewrite import extensions.

So I thought to check with you and see if there can be a mode that only allows `.js` extensions, so that the code can break early in the development lifecycle

**Comment by antfu** [comment]
I guess it's better to set up an eslint rule?

**Comment by thetutlage** [comment]
Sounds like a plan. No idea why I didn't think about it. Thanks 👍
