### ISSUE TITLE
tsconfig paths support?

### ISSUE THREAD

**Issue by seonglae** [antfu/esbuild-node-loader#8]
I'm not sure that this module is trying to make compatible with `tsconfig.json`

When I use esmo, I got some error like this
```bash
esmo ./folder/file.ts
```

### My `tsconfig.json`
```json
{
"paths": {
      "@/*": ["./src/*"],
      "~/*": ["./*"]
  }
}
```

Because there is
```ts
import { func } from '@/module'
```

This error occurs
```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@/parsers' imported from
```

Is there a plan to resolve this issue or support usage like this?

**Comment by antfu** [comment]
Good catch, PR Welcome.
